package com.dam.jobService.types;

public enum TaskType {
	
	DEPOT_INVEST_INTENT,
	DEPOT_SELL_INTENT,
	DEPOT_TRANSFER_TO_DEPOT_INTENT,
	DEPOT_TRANSFER_TO_ACCOUNT_INTENT,
	DEPOT_DEPOSIT_INTENT,
	DEPOT_DEBIT_INTENT;

}
